<a href="https://colab.research.google.com/github/GouravNayak/Data-Mining/blob/master/Misc/AutoScaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from sklearn import preprocessing

In [7]:
dataset = np.array([[1,2,-2],[0,3,4],[2,1,1]])
print(dataset)

[[ 1  2 -2]
 [ 0  3  4]
 [ 2  1  1]]


In [23]:
x_scaled = preprocessing.scale(dataset, axis=0)
print(x_scaled)

[[ 0.          0.         -1.22474487]
 [-1.22474487  1.22474487  1.22474487]
 [ 1.22474487 -1.22474487  0.        ]]


In [27]:
x_scaled.std(axis=0)


array([1., 1., 1.])

In [26]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [28]:
test_dataset = np.array([[0,0,-1],[-1,1,1],[1,-1,0]])

In [29]:
test_dataset.std(axis=0)

array([0.81649658, 0.81649658, 0.81649658])